from .add_color import add_color
from .apply_func import apply_func
from .blackwhite import blackwhite
from .flips import flips
from .prepro import prepro
#from .reduce_dimension import reduce_dimension
from .resize import resize
from .rotations import rotations
from .subsample import subsample
from .smartsample import smartsample
from .classsample import classsample
from .grapho import grapho
from .crop import crop
from .normalize import normalize
from .featurebagging import featurebagging
from .trainsample import trainsample
